urls.py
from django.conf.urls.defaults import patterns, include, url
from django.conf import settings
from django.contrib import admin, databrowse

from obras.models import Proveedor, Categoria, Gasto, DetalleGasto, Concepto, Obra
from django.views.generic.simple import redirect_to
from ajax_select import urls as ajax_select_urls

admin.autodiscover()
databrowse.site.register(Proveedor)
databrowse.site.register(Categoria)
databrowse.site.register(Gasto)
databrowse.site.register(DetalleGasto)
databrowse.site.register(Concepto)
databrowse.site.register(Obra)

urlpatterns = patterns('',
    
    ('^$', redirect_to, {'url':'admin'}),    
    
    #SOLO PARA DESARROLLO    
    (r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    url(r'^admin/', include(admin.site.urls)),
    (r'^databrowse/(.*)', databrowse.site.root),
    (r'^obras/', include('obras.urls')),
    
    # include the lookup urls
    (r'^admin/lookups/', include(ajax_select_urls)),
)

obras/generic_report/forms.py
from django import forms
from django.contrib.admin import widgets
from datetime import date
from obras import utils
from obras.report_forms import BaseReportForm
from obras import models
from obras.generic_report import report_items

class ElementSelectForm(forms.Form):
    ELEMENTO_CHOICES = (('HON', 'Honorario'), 
                        ('DET', 'Detalle de gasto'),
                        ('PAG', 'Pago de obra'),
                        ('PRE', 'Presupuesto proveedor'),
                        ('TSY', 'Presupuesto honorarios TSYA'),
                        )
    elemento = forms.ChoiceField(choices=ELEMENTO_CHOICES)
    

class GenericReportForm(BaseReportForm):
    
    desde = forms.DateField(widget=widgets.AdminDateWidget(), initial=utils.first_of_month)
    hasta = forms.DateField(widget=widgets.AdminDateWidget(), initial=date.today)
    
    agrupar = forms.ChoiceField(label='Agrupar por', choices=[], initial='NO') 
    
    total_general = forms.BooleanField(initial=True, required=False)
    totales_parciales = forms.BooleanField(initial=False, required=False)
    
    def __init__(self, *args, **kwargs):
        super(GenericReportForm, self).__init__(*args, **kwargs)
        self._agregar_campos()
        self._agregar_filtros_querysets()
        self._update_agrupar_choices()
    
    def _model(self):
        return self.Meta.report_class.Meta.model
    
    def _update_agrupar_choices(self):
        choices = [('NO', 'No agrupar')]
        
        index = 0
        for campo in self.Meta.agrupar_por:
            choices.append((campo,  utils.field_pretty_print(campo, 
                                                    self._model())))
            index += 1
        
        self.fields['agrupar'].choices = choices
    
    def _agregar_campos(self):
        for field_name in self.Meta.campos:
            label = utils.field_pretty_print(field_name, self._model())
            form = forms.BooleanField(required=False, initial=True, 
                                      label=label)
                                      
            self.fields['campo_' + field_name] = form
        
    def _agregar_filtros_querysets(self):
        for field_name in self.Meta.agrupar_por:
            
            model_class = self.Meta.agrupar_por[field_name]
            
            form = forms.ModelChoiceField(queryset=model_class.objects, 
                        required=False)
                        
            self.fields[field_name] = form
            
    def get_campos_fields(self):
        return [self['campo_' + f] for f in self.Meta.campos]
    
    def get_grupos_fields(self):
        return [self[f] for f in self.Meta.agrupar_por]
    
    
    def _get_agrupar_choice(self, grupo):
        """ 
        Devuelve el nombre del campo del modelo al que corresponde el
        grupo indicado.
        
        por ejemplo, dado 'cliente' devuelve 'obra__cliente' si esta entre los
        campos o el mismo nombre del grupo.
        """
        
        for campo in self.Meta.campos:
            if campo.endswith(grupo):
                return campo
        
        return grupo
    
    def _get_filtros_dict(self):
        """ 
        Devuelve un diccionario de instancias por las que filtrar los elementos
        del reporte. 
        """
        
        filtros = {}
        
        for field in self.Meta.agrupar_por:
            value = self.cleaned_data.get(field)
            if value:
                filtros[self._get_agrupar_choice(field)] = value
        
        return filtros
    
    def _make_context_dict(self):
        
        desde = self.cleaned_data['desde']
        hasta = self.cleaned_data['hasta']
        parciales = self.cleaned_data['totales_parciales']
        general = self.cleaned_data['total_general']
        
        columnas = [c for c in self.Meta.campos 
                            if self.cleaned_data['campo_' + c]]
        
        filtros = self._get_filtros_dict()
        
        if self.cleaned_data['agrupar'] == 'NO':
            agrupar_por = None
        else:
            agrupar_por = self._get_agrupar_choice(str(
                                                self.cleaned_data['agrupar']))
        
        reporte = self.Meta.report_class(desde, hasta, columnas, 
                               agrupar_por, filtros,
                               parciales, general)
        
        return { 'fecha': date.today(), 'pagesize': 'A4', 
                'columnas' : columnas, 'reporte' : reporte}
    
    
    
    class Meta:
        """ Modelo al que corresponden los items del reporte. """
        report_class = None
        
        """ 
        Lista de los campos a ser incluidos en el reporte. Son redefinidos por 
        las subclases. 
        """
        campos = []
        
        """ 
        Campos por los que se pueden agrupar los items del reporte.
        Debe ser un diccionario con items del estilo field_name:model_class.
        
        Las opciones de agrupado tambien seran las de filtrado.       
        """
        agrupar_por = {}
        

class HonorarioReportForm(GenericReportForm):
    
    class Meta:
        report_class = report_items.HonorarioReport
        campos = ['tipo_factura', 'n_factura', 'fecha', 'obra', 
                  'obra__pais', 'obra__cliente', 'obra__estado_obra',                  
                  'imp_neto', 'imp_a_cobrar']
        agrupar_por = {'obra' : models.Obra, 'pais' : models.Pais, 
                       'cliente' : models.Cliente, 'estado_obra' : models.EstadoObra}

class GastoReportForm(GenericReportForm):
    
    class Meta:
        report_class = report_items.GastoReport
        campos = ['tipo', 'numero', 'fecha_op', 'proveedor', 'imp_neto', 
                  'get_importe_a_pagar', 'total_aplicaciones']
        agrupar_por = {'proveedor': models.Proveedor }

class DetalleReportForm(GenericReportForm):
    
    class Meta:
        report_class = report_items.DetalleReport
        campos = ['concepto', 'concepto__categoria', 
                  'obra', 'obra__pais', 'obra__cliente', 'obra__estado_obra',
                  'gasto__fecha_op', 'gasto__proveedor', 'gasto', 
                  'imp_neto', 'get_importe_a_pagar']
        
        agrupar_por = {'obra' : models.Obra,
                       'pais' : models.Pais, 
                       'cliente' : models.Cliente, 
                       'estado_obra' : models.EstadoObra,
                       'proveedor' : models.Proveedor,
                       'concepto' : models.Concepto,
                       'categoria' : models.Categoria}

class PagoReportForm(GenericReportForm):
    
    class Meta:
        report_class = report_items.PagoReport
        campos = ['tipo_factura', 'n_factura', 'fecha', 'presupuesto', 
                  'presupuesto__proveedor', 'presupuesto__obra',
                  'presupuesto__obra__pais', 'presupuesto__obra__cliente',
                  'presupuesto__obra__estado_obra',
                  'imp_neto', 'imp_a_cobrar']
        agrupar_por = {'obra' : models.Obra, 
                       'pais' : models.Pais, 
                       'cliente' : models.Cliente, 
                       'estado_obra' : models.EstadoObra,
                       'proveedor' : models.Proveedor, 
                       }

class PresupuestoReportForm(GenericReportForm):
    
    class Meta:
        report_class = report_items.PresupuestoReport
        campos = ['num_pres_ext', 'fecha_emision', 'proveedor', 'obra',
                  'importe_contratado', 'total_aplicaciones']
        agrupar_por = {'obra' : models.Obra, 
                       'proveedor' : models.Proveedor}

class PresupuestoTSYAReportForm(GenericReportForm):
    
    class Meta:
        report_class = report_items.PresupuestoTSYAReport
        campos = ['fecha_emision', 'obra', 
                  'obra__pais', 'obra__estado_obra',
                  'importe_contratado',
                  'importe_proyectado', 'obra__total_aplicaciones']
        agrupar_por = {'obra' : models.Obra,
                       'pais' : models.Pais, 
                       'estado_obra' : models.EstadoObra,}

obras/generic_report/views.py
from django.http import HttpResponse
from django.utils import simplejson
from django.template.loader import get_template
from django.template.context import Context
from obras.generic_report import forms
from obras.views.report_views import report_view


#Ajax view for getting the form html
generic_forms = {'HON' : forms.HonorarioReportForm, 
                 'GAS' : forms.GastoReportForm, 
                 'DET' : forms.DetalleReportForm,
                 'PAG' : forms.PagoReportForm,
                 'PRE' : forms.PresupuestoReportForm,
                 'TSY' : forms.PresupuestoTSYAReportForm}

def get_form(request, form_template):
    elemento = request.GET['elemento']
    form = generic_forms[elemento]()
    
    template = get_template(form_template)
    html = template.render(Context({'form' : form}))
        
    return HttpResponse(simplejson.dumps({'form' : html}), 
                            mimetype='application/json')
    
    
def generic_report_view(request, *args, **kwargs):
    
    form_class = forms.ElementSelectForm
    
    if request.method == 'POST':
        form = forms.ElementSelectForm(request.POST)
        if form.is_valid():
            
            form_class = generic_forms[form.cleaned_data['elemento']]
    
    return report_view(request, form_class, *args, **kwargs)
    
    

obras/views/report_views.py
'''
Views for generating reports.
'''

from django import http
from django.template import RequestContext
from django.shortcuts import render_to_response
from obras import report_forms
import datetime


def make_response(content, filename, extension='pdf', mimetype='application/pdf'):
    """
    Takes a pdf form output and returns the HttpResponse for the attachment,
    with the given filename and the current datetime.
    """
    
    response = http.HttpResponse(content, mimetype=mimetype)
                
    filename += datetime.datetime.now().strftime('-%d-%m-%y-%H-%M-%S')
    response['Content-Disposition'] = 'attachment; filename=%s.%s' % (
                                                        filename, extension)
                    
    return response
    

def report_view(request, form_class, report_name, page_template, 
                pdf_template, xls_template, report_filename):
    
    if request.method == 'POST':
        form = form_class(data=request.POST)
        if form.is_valid():
            
            if form.cleaned_data['formato'] == 'PDF':
                result = form.get_pdf(request, pdf_template)
            
                if result: #errores en pdf         
                    return make_response(result, report_filename)
            
            else:
                result = form.get_xls(request, xls_template)
                return make_response(result, report_filename, 'xls', 
                                     'text/xls')
    
    else:
        form = form_class()
    
    return render_to_response(page_template, {'title':report_name,
                                         'form':form },                                  
                                  context_instance = RequestContext(request),)


def plan_cuentas(request, report_template, pdf_filename):
    form = report_forms.PlanCuentasReportForm()
    result = form.get_pdf(request, report_template)
            
    return make_response(result, pdf_filename + '.pdf')


def inline_report_view(request, object_id, report_template, pdf_filename,
                       model_class, form_class, field_name):
    object = model_class.objects.get(id=object_id)
    form =  form_class()
    
    #fixme ugly
    form.cleaned_data = { field_name : object }
    result = form.get_pdf(request, report_template)
    
    return make_response(result, pdf_filename + '.pdf')

templates/reports/base_report.html
<html>
<head>
<title>{% block file_title %}TSYA{% endblock %}</title>
<style>
    
    #header {
    	margin-bottom: 20px;
    }
    
    
    #header tr {
        font-weight: bold;
        border-bottom: 2px solid black;
    }
    
    #header td {
    	vertical-align: middle;
    	text-align: center;
    	}
    
    h1 {
    	font-size: 18pt;    	    	    	
    }
    
    #footerContent {
    	padding-top: 10px;
    	font-size: 12px;
    	
    }
    
@page {
    margin: 1cm;
    margin-bottom: 4cm;
    {% block page_styles %}{% endblock %}
	
  @frame footer {
    -pdf-frame-content: footerContent;
    bottom: 1cm;
    margin-left: 1cm;
    margin-right: 1cm;
    height: 2.5cm;
    text-align: right;
  }
  
  {% block extra_frames %}{% endblock %}
  
}



{% block extrastyle %}
	#mid {
        text-align: left;
        border-bottom: 1px solid;
    }
	
	
	#report{
    	padding: 2px 2px 2px 2px;
        font-size: 12px;
        text-align: left;
    }
    
    #report table {
    	border: 0.5px solid;
    	text-align: left;
    	
    }
    
    #report th{
    	font-weight: bold;
    }


{% endblock %}
    
</style>
</head>
<body>
   <table border="2" bordercolor="#000000" keepmaxheight="20cm" width="100%">
{% block page_header %}
<table id="header">
	{% if format == 'pdf' %}
    <tr style="width:100%">
        <td><img id="logo" src="{{ MEDIA_URL }}images/report-logo.jpg"></td>
        <td><h1>
    {% else %}
    <tr style="width:100%">
        <td><img id="logo" src="http://antingprojects.com.ar/media/images/report-logo.jpg"></td>
    <tr><td colspan={% block colspan1 %}5{% endblock %} style="height:150px;"></td></tr>
    <tr>
    	<td colspan={% block colspan2 %}5{% endblock %}><h1>
    {% endif %}
    {% block page_title %}{% endblock %}</h1>{% block page_header_extra %}{% endblock %}</td>
    
    </tr>
</table>

{% endblock %}
	
<div id="report">
{% block report %}
	
		<div id="mid">
		{% block report_header %}
		{% endblock %}
		</div>
		
		{% block report_content %}{% endblock%}
	
{% endblock %}
</div>
<div id="footerContent">
{% block page_footer %}
	<table>
		<tr style="border-bottom: 0.5px solid; ">
            <td>{% now "d/m/Y" %}</td>
            <td style="text-align: right;">
                Página
                <pdf:pagenumber>
            </td>	
		</tr>
	</table>
	<p style="font-size: 8pt; text-align:center;">TSYA S.A. Boyacá 971 C1406BHQ Ciudad autónoma de Buenos Aires . Argentina . tel/fax: 4582-3558 estudio@tsya.net . www.tsya.net</p>
{% endblock %}   
</div>
</table>
</body>
</html>
 

templates/reports/ccanalitico_report.html
{% extends 'reports/base_report.html' %}

{% load obras_tags %}

{% block file_title %}TSYA - Honorarios{% endblock %}

{% block page_title %}Reporte Honorarios <br/>Cuenta corriente analítico {% endblock %}

{% block extrastyle %}
	
	
	#report{
    	padding: 2px 2px 2px 2px;
        font-size: 12px;
        text-align: left;        
    }
    
    #report table {
    	border: 0;
    	font-size: 11px;
    	text-align: left;
    	
    }
    
    #report th{
    	font-weight: bold;
    	border-top: 0.5px solid;
    	border-bottom: 0.5px solid;
    }
	
	#mid {
        text-align: left;
        
    }
    
    #mid td, #mid p{
        font-size:13px;
    }
    
    
{% endblock %}


{% block report_content %}
<h2 style="-pdf-keep-with-next:false;">Honorarios del {{ desde|date:"SHORT_DATE_FORMAT" }} al {{ hasta|date:"SHORT_DATE_FORMAT" }}</h2>
<br/>
<hr/>
<br/>
{% for item in items %}
<h2>Resumen:</h2>
<table>
<tr><td>Contratado:</td><td>{{ item.pres.importe_contratado }}</td><td>{{ item.pres.importe_contratado|percentage:item.pres.importe_contratado }}</td><td>Proyectado:</td><td>{{ item.pres.importe_proyectado }}</td></tr>
<tr><td>Cobrado:</td><td>{{ item.obra.total_aplicaciones }}</td><td>{{ item.obra.total_aplicaciones|percentage:item.pres.importe_contratado }}</td><td colspan=2></td></tr>
<tr><td>A cobrar:</td><td>{{ item.total }}</td><td>{{ item.total|percentage:item.pres.importe_contratado }}</td><td colspan=2></td></tr>
</table>

<hr/>
<p>{{ item.obra.id }} - {{ item.obra.nombre }} - {{ item.obra.cliente.nombre }}</p>

<table cellspacing="0" id="content">
    <tr>
        <th>Comprobante</th>
        <th>Emisión</th>
        <th>Tipo y N°</th>
        <th>Compr.</th>
        <th>Detalle</th>
        <th>Contratado</th>
        <th>Proyectado</th>
    </tr>
    
    {% for x in item.principal %}
        {% if forloop.first %}
        <tr>
            <td>Presupuesto</td>
            <td>{{ x.0.fecha_emision|date:"SHORT_DATE_FORMAT" }}</td>
            <td></td>
            <td></td>
            <td>{{ x.0.descripcion }}</td>
            <td>{{ x.1 }}</td>
            <td>{{ item.pres.importe_proyectado }}</td>
        </tr>
        {% else %}               
            
        {% comment %} pago honorarios == x {% endcomment %}    
            <tr>
                <td>Pago</td>
                <td>{{ x.0.fecha|date:"SHORT_DATE_FORMAT" }}</td>
                <td>{{ x.0.tipo_factura }}</td>
                <td>{{ x.0.n_factura }}</td>
                <td>{{ x.0.descripcion }}</td>
                <td>{{ x.1 }}</td>
                <td></td>
            </tr>
        {% endif %}
    {% endfor %}
    <tr>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td><b>{{ item.total }}</b></td>
    <td><b>{{ item.pres.importe_proyectado }}</b></td>
    </tr>
</table>
<hr/>
<br/>
<br/>
{% endfor %}
{% endblock%}

templates/reports/factura_report.html
{% extends 'reports/base_report.html' %}

{% block file_title %}TSYA - Facturación{% endblock %}

{% block page_title %}Certificado de facturación{% endblock %}

{% block extrastyle %}
	
	
	#report{
    	padding: 2px 2px 2px 2px;
        font-size: 12px;
        text-align: left;        
    }
    
    #report table {
    	border: 0;
    	font-size: 11px;
    	text-align: left;
    	
    }
    
    #report th{
    	font-weight: bold;
    }
	
	#mid {
        text-align: left;
        border-bottom: 1px solid;
    }
    
    #mid td, #mid p{
        font-size:13px;
    }
    
    
{% endblock %}

{% block report_header %}
<table>
<tr><td><h1>{{ honorario.tipo_factura.descripcion }}</h1></td><td></td><td style="text-align: right;"><h1>N°:{{ honorario.n_factura }}</h1></td></tr>
<tr><td>Fecha factura:</td><td colspan=2> {{ honorario.fecha|date:"SHORT_DATE_FORMAT" }}</td></tr>
<tr><td>Obra:</td><td colspan=2> {{ honorario.obra }}</td></tr>
<tr><td>Descripción:</td><td colspan=2> {{ honorario.descripcion }}</td></tr>
<tr><td>Importe neto:</td><td colspan=2> {{ honorario.get_moneda_display }} ${{ honorario.imp_neto }}</td></tr>
<tr><td>Importe a cobrar:</td><td colspan=2> {{ honorario.get_moneda_display }} ${{ honorario.imp_a_cobrar }}</td></tr>
</table>

{% endblock %}


{% block colspan1 %}6{% endblock %}
{% block colspan2 %}6{% endblock %}

{% block report_content %}
<hr/>
<h2>Datos del presupuesto</h2>
<table>
<tr><td>Fecha de emisión:</td><td colspan=2> {{ presupuesto.fecha_emision|date:"SHORT_DATE_FORMAT" }}</td></tr>
<tr><td>Obra:</td><td colspan=2> {{ presupuesto.obra }}</td></tr>
<tr><td>Estado de obra:</td><td colspan=2> {{ presupuesto.obra.estado_obra.descripcion }}</td></tr>
<tr><td>Monto proyectado:</td><td colspan=2>${{ presupuesto.importe_proyectado }}</td></tr>
<tr><td>Descripción:</td><td colspan=2>{{  presupuesto.descripcion }}</td></tr>
<tr><td>Observaciones:</td><td colspan=2>{{  presupuesto.observaciones }}</td></tr>
</table>


{% endblock%}

templates/reports/facturas_honorarios_report.html
{% extends 'reports/base_report.html' %}

{% load obras_tags %}

{% block file_title %}TSYA - Presupuestos{% endblock %}

{% block page_title %}Reporte Facturas<br/> Honorarios TSYA {% endblock %}

{% block extrastyle %}
	
	
	#report{
    	padding: 2px 2px 2px 2px;
        font-size: 12px;
        text-align: left;        
    }
    
    #report table {
    	border: 0;
    	font-size: 11px;
    	text-align: left;
    	
    }
    
    #report th{
    	font-weight: bold;
    	border-top: 0.5px solid;
    	border-bottom: 0.5px solid;
    }
	
	#mid {
        text-align: left;
        
    }
    
    #mid td, #mid p{
        font-size:13px;
    }
    
    
{% endblock %}


{% block colspan1 %}7{% endblock %}
{% block colspan2 %}7{% endblock %}

{% block report_content %}
<h2 style="-pdf-keep-with-next:false;">Facturas del {{ desde|date:"SHORT_DATE_FORMAT" }} al {{ hasta|date:"SHORT_DATE_FORMAT" }}</h2>
<p><b>
{% if estado %}Estado: {{ estado }}. {% endif %}
{% if pais %}Pais: {{ pais }}. {% endif %}
{% if cliente %}Cliente: {{ cliente }}. {% endif %}</b>
</p>

<table cellspacing="0" id="content">
    <thead>
    <tr>
        <th>ID</th>
        <th>Obra</th>
        <th>Tipo de compr.</th>
        <th>Número</th>
        <th>Fecha</th>
        <th>Importe neto</th>
        <th>Importe a cobrar</th>
    </tr>
    </thead>

	{% for obra in items %}
    <tr>
    	<td style="width: 50px;">{{ obra.0.id }}</td>
     	<td style="width: 200px;">{{ obra.0.nombre }}</td>
     	<td colspan=5></td>
    </tr>
     
    {% for honorario in obra.1 %}
    	<tr>
     		<td colspan=2></td>
     		<td>{{ honorario.tipo_factura }}</td>
     		<td>{{ honorario.n_factura }}</td>
     		<td>{{ honorario.fecha|date:"SHORT_DATE_FORMAT" }}</td>
     		<td style="text-align: right;">${{ honorario.imp_neto }}</td>
     		<td style="text-align: right;">${{ honorario.imp_a_cobrar }}</td>
     	</tr>     	
	{% endfor %}
    <tr><td colspan=7></td></tr>
	<tr style="font-weight:bold; text-align: right;"><td colspan=4></td><td>Total obra:</td><td>${{ obra.2 }}</td><td>${{ obra.3 }}</td></tr>
    {% endfor %}
	<tr style="font-weight:bold; text-align: right;"><td colspan=4></td><td>Total general:</td><td>${{ total_neto }}</td><td>${{ total_a_cobrar }}</td></tr>

</table>

{% endblock%}

templates/reports/gastos_x_obra.html
{% for categoria in items %}
	<div class="categoria">{{ categoria.0 }} ${{ categoria.2 }}</div>
	{% for superconcepto in categoria.1 %}
	    <div class="superconcepto">{{ superconcepto.0 }} ${{ superconcepto.2 }}</div>
		{% for subconcepto in superconcepto.1 %}
			<div class="subconcepto">{{ subconcepto.0 }} ${{ subconcepto.2 }}</div>
				<table class="gastos">
					<thead>
                        <tr>
                            <th>Fecha</th>
                            <th >Nro. Orden</th>
                            <th >Comp. externo</th>
                            <th>Proveedor</th>
                            <th>Importe no gravado</th>
                        </tr>
					</thead>
					<tbody>
					{% for gasto in subconcepto.1 %}
					<tr>
					    <td style="width=80px;">{{ gasto.gasto.fecha_op|date:"SHORT_DATE_FORMAT" }}</td>
						<td style="width=100px;">{{ gasto.gasto.id }}</td>
						<td style="width=100px;">{{ gasto.gasto.numero }}</td>
						<td style="width=250px;">{{ gasto.gasto.proveedor }}</td>
						<td style="width=150px;">${{ gasto.imp_neto }}</td>
					</tr>						
					{% endfor %}	
					</tbody>					
				</table>
                <pdf:spacer height="0.5cm" />

		{% endfor %} {# /Subconceptos #}
    {% endfor %}  {# /Superconceptos #}
{% endfor %} {# /Categorias #}

templates/reports/generic_report_page.html
{% extends "admin/base_site.html" %}

{% block content %}
    
    <form method="POST" action="">{% csrf_token %}
	    <table>
	    	{{ form.as_table }}
	    </table>
        <div id="form_container"></div>    
        <input id="boton_aceptar" type="submit" value="Submit">
    </form>
{% endblock %}


{% block extrahead %} 
<link rel="stylesheet" type="text/css" href="/admin_media/css/forms.css" />
<script type="text/javascript" src="{{ MEDIA_URL }}js/jquery-1.4.2.js"></script>

    <script type="text/javascript" src="/admin/jsi18n/"></script>
    <script type="text/javascript" src="{% load adminmedia %}{% admin_media_prefix %}js/core.js"></script>
    <script type="text/javascript" src="{% admin_media_prefix %}js/calendar.js"></script>
    <script type="text/javascript" src="{% admin_media_prefix %}js/admin/DateTimeShortcuts.js"></script>
    
<link type="text/css" href="{{ MEDIA_URL }}css/custom-theme/jquery-ui-1.8.6.custom.css" rel="Stylesheet" />
<script type="text/javascript" src="{{ MEDIA_URL }}js/jquery-ui-1.8.6.custom.min.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/combo_box.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/calendar_fix.js"></script>

{{ block.super }}

<script type="text/javascript">
$(function() {	

	$('#id_elemento').change(function(){
		$.ajax({
		      type: 'GET',
		      url: "{% url get_form_generico %}",
		      data: {'elemento': $('#id_elemento').val()},
		      success: function(data, status) {
		        $('#form_container').html(data.form);
		        update_form_events();
		      },
		      dataType: "json"
		    });

		}).trigger('change');

});

function update_form_events() {

	DateTimeShortcuts.init();
	$('#id_obra').combobox();
	$('#id_proveedor').combobox();
	$('#id_cliente').combobox();
	//$('#id_gasto').combobox();
	$('#id_presupuesto').combobox();

	kill_today();
}
</script>

{% endblock %} 